In [ ]:
import pandas as pd
import numpy as np

In [26]:
info= pd.read_csv('C:\\Users\\ljy25\\etri\\data\\user_info_2020.csv')
info

    userId gender  age handed  height  weight     startDt       endDt
0   user24      F   26  Right     165      67  2020-08-29  2020-09-27
1   user23      M   35  Right     177      84  2020-08-31  2020-09-27
2   user05      M   31  Right     177      75  2020-08-31  2020-09-27
3   user04      M   28  Right     171      70  2020-08-31  2020-09-27
4   user12      F   30  Right     160      54  2020-08-30  2020-09-27
5   user08      M   32  Right     180      84  2020-08-31  2020-09-25
6   user02      F   25   Left     168      81  2020-08-31  2020-09-27
7   user10      M   25  Right     184      77  2020-08-30  2020-09-27
8   user03      F   32  Right     166      62  2020-08-29  2020-09-27
9   user11      M   32  Right     175      78  2020-08-30  2020-09-27
10  user28      M   31  Right     169      79  2020-08-31  2020-09-26
11  user21      F   26  Right     166      57  2020-08-29  2020-09-27
12  user26      F   27  Right     160      47  2020-08-31  2020-09-26
13  user01      M   27   Left     167      76  2020-08-30  2020-09-27
14  user22      F   30  Right     163      68  2020-09-01  2020-09-27
15  user29      M   29  Right     169      63  2020-08-30  2020-09-27
16  user25      M   27  Right     182      72  2020-08-31  2020-09-27
17  user09      M   20  Right     170      80  2020-08-31  2020-09-27
18  user30      M   26  Right     174      58  2020-08-31  2020-09-27
19  user07      M   30  Right     173      83  2020-08-31  2020-09-27
20  user27      F   28  Right     170      60  2020-09-04  2020-10-02
21  user06      F   22  Right     164      70  2020-09-11  2020-10-08

In [27]:
info = info.sort_values(['userId'],axis=0).reset_index(drop=True)
info

    userId gender  age handed  height  weight     startDt       endDt
0   user01      M   27   Left     167      76  2020-08-30  2020-09-27
1   user02      F   25   Left     168      81  2020-08-31  2020-09-27
2   user03      F   32  Right     166      62  2020-08-29  2020-09-27
3   user04      M   28  Right     171      70  2020-08-31  2020-09-27
4   user05      M   31  Right     177      75  2020-08-31  2020-09-27
5   user06      F   22  Right     164      70  2020-09-11  2020-10-08
6   user07      M   30  Right     173      83  2020-08-31  2020-09-27
7   user08      M   32  Right     180      84  2020-08-31  2020-09-25
8   user09      M   20  Right     170      80  2020-08-31  2020-09-27
9   user10      M   25  Right     184      77  2020-08-30  2020-09-27
10  user11      M   32  Right     175      78  2020-08-30  2020-09-27
11  user12      F   30  Right     160      54  2020-08-30  2020-09-27
12  user21      F   26  Right     166      57  2020-08-29  2020-09-27
13  user22      F   30  Right     163      68  2020-09-01  2020-09-27
14  user23      M   35  Right     177      84  2020-08-31  2020-09-27
15  user24      F   26  Right     165      67  2020-08-29  2020-09-27
16  user25      M   27  Right     182      72  2020-08-31  2020-09-27
17  user26      F   27  Right     160      47  2020-08-31  2020-09-26
18  user27      F   28  Right     170      60  2020-09-04  2020-10-02
19  user28      M   31  Right     169      79  2020-08-31  2020-09-26
20  user29      M   29  Right     169      63  2020-08-30  2020-09-27
21  user30      M   26  Right     174      58  2020-08-31  2020-09-27

In [28]:
info.loc[info['gender']=='M','gender'] = 0
info.loc[info['gender']=='F','gender'] = 1
info

    userId gender  age handed  height  weight     startDt       endDt
0   user01      0   27   Left     167      76  2020-08-30  2020-09-27
1   user02      1   25   Left     168      81  2020-08-31  2020-09-27
2   user03      1   32  Right     166      62  2020-08-29  2020-09-27
3   user04      0   28  Right     171      70  2020-08-31  2020-09-27
4   user05      0   31  Right     177      75  2020-08-31  2020-09-27
5   user06      1   22  Right     164      70  2020-09-11  2020-10-08
6   user07      0   30  Right     173      83  2020-08-31  2020-09-27
7   user08      0   32  Right     180      84  2020-08-31  2020-09-25
8   user09      0   20  Right     170      80  2020-08-31  2020-09-27
9   user10      0   25  Right     184      77  2020-08-30  2020-09-27
10  user11      0   32  Right     175      78  2020-08-30  2020-09-27
11  user12      1   30  Right     160      54  2020-08-30  2020-09-27
12  user21      1   26  Right     166      57  2020-08-29  2020-09-27
13  user22      1   30  Right     163      68  2020-09-01  2020-09-27
14  user23      0   35  Right     177      84  2020-08-31  2020-09-27
15  user24      1   26  Right     165      67  2020-08-29  2020-09-27
16  user25      0   27  Right     182      72  2020-08-31  2020-09-27
17  user26      1   27  Right     160      47  2020-08-31  2020-09-26
18  user27      1   28  Right     170      60  2020-09-04  2020-10-02
19  user28      0   31  Right     169      79  2020-08-31  2020-09-26
20  user29      0   29  Right     169      63  2020-08-30  2020-09-27
21  user30      0   26  Right     174      58  2020-08-31  2020-09-27

In [29]:
info.loc[info['handed']=='Left', 'handed'] = 0
info.loc[info['handed']=='Right', 'handed'] = 1
info

    userId gender  age handed  height  weight     startDt       endDt
0   user01      0   27      0     167      76  2020-08-30  2020-09-27
1   user02      1   25      0     168      81  2020-08-31  2020-09-27
2   user03      1   32      1     166      62  2020-08-29  2020-09-27
3   user04      0   28      1     171      70  2020-08-31  2020-09-27
4   user05      0   31      1     177      75  2020-08-31  2020-09-27
5   user06      1   22      1     164      70  2020-09-11  2020-10-08
6   user07      0   30      1     173      83  2020-08-31  2020-09-27
7   user08      0   32      1     180      84  2020-08-31  2020-09-25
8   user09      0   20      1     170      80  2020-08-31  2020-09-27
9   user10      0   25      1     184      77  2020-08-30  2020-09-27
10  user11      0   32      1     175      78  2020-08-30  2020-09-27
11  user12      1   30      1     160      54  2020-08-30  2020-09-27
12  user21      1   26      1     166      57  2020-08-29  2020-09-27
13  user22      1   30      1     163      68  2020-09-01  2020-09-27
14  user23      0   35      1     177      84  2020-08-31  2020-09-27
15  user24      1   26      1     165      67  2020-08-29  2020-09-27
16  user25      0   27      1     182      72  2020-08-31  2020-09-27
17  user26      1   27      1     160      47  2020-08-31  2020-09-26
18  user27      1   28      1     170      60  2020-09-04  2020-10-02
19  user28      0   31      1     169      79  2020-08-31  2020-09-26
20  user29      0   29      1     169      63  2020-08-30  2020-09-27
21  user30      0   26      1     174      58  2020-08-31  2020-09-27

In [31]:
info.to_csv('C:\\Users\\ljy25\\etri\\data\\changed_user_info_2020.csv',index=False)