In [15]:
import numpy as np
import pandas as pd

In [16]:
user_survey_2020 = pd.read_csv("C:\\Users\\ljy25\\etri\\data\\user_survey_2020.csv")
user_survey_2020

,userId,date,amPm,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,am,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,user24,2020-08-29,pm,2020-08-29 21:23,2020-08-29 21:23,NaN,NaN,NaN,NaN,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN
2,user24,2020-08-30,am,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,user24,2020-08-30,pm,2020-08-30 22:43,2020-08-30 22:43,NaN,NaN,NaN,NaN,NaN,4.0,5.0,2.0,coffee,200.0,NaN,NaN
4,user24,2020-08-31,am,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,user06,2020-10-06,pm,2020-10-07 0:07,2020-10-07 0:08,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,NaN
1226,user06,2020-10-07,am,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227,user06,2020-10-07,pm,2020-10-08 1:57,2020-10-08 1:57,NaN,NaN,NaN,NaN,NaN,5.0,2.0,3.0,coffee,250.0,NaN,NaN
1228,user06,2020-10-08,am,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1229,user06,2020-10-08,pm,2020-10-08 23:30,2020-10-08 23:31,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [17]:
user_survey_2020 = user_survey_2020.backfill(limit=1)
user_survey_2020

C:\Users\ljy25\AppData\Local\Temp\ipykernel_6844\2501466442.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  user_survey_2020 = user_survey_2020.backfill(limit=1)

,userId,date,amPm,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,am,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
1,user24,2020-08-29,pm,2020-08-29 21:23,2020-08-29 21:23,3.0,2.0,2.0,2.0,3.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
2,user24,2020-08-30,am,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
3,user24,2020-08-30,pm,2020-08-30 22:43,2020-08-30 22:43,3.0,2.0,2.0,3.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
4,user24,2020-08-31,am,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,coffee,200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,user06,2020-10-06,pm,2020-10-07 0:07,2020-10-07 0:08,2.0,9.0,4.0,2.0,3.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
1226,user06,2020-10-07,am,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
1227,user06,2020-10-07,pm,2020-10-08 1:57,2020-10-08 1:57,3.0,0.0,4.0,2.0,2.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
1228,user06,2020-10-08,am,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,3.0,2.0,2.0,coffee,300.0,NaN,NaN
1229,user06,2020-10-08,pm,2020-10-08 23:30,2020-10-08 23:31,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [18]:
tmp = user_survey_2020
tmp = tmp.drop(tmp[tmp['amPm']=='pm'].index)
tmp

,userId,date,amPm,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,am,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
2,user24,2020-08-30,am,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
4,user24,2020-08-31,am,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,coffee,200.0,NaN,NaN
6,user24,2020-09-01,am,2020-09-01 6:20,2020-09-01 6:20,4.0,0.0,4.0,4.0,3.0,5.0,4.0,3.0,coffee,150.0,NaN,NaN
8,user24,2020-09-02,am,2020-09-02 9:02,2020-09-02 9:02,4.0,0.0,4.0,2.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,user06,2020-10-04,am,2020-10-04 12:03,2020-10-04 12:03,4.0,0.0,4.0,4.0,4.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN
1222,user06,2020-10-05,am,2020-10-05 12:16,2020-10-05 12:16,4.0,0.0,4.0,4.0,3.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
1224,user06,2020-10-06,am,2020-10-06 11:37,2020-10-06 11:37,4.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
1226,user06,2020-10-07,am,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
1228,user06,2020-10-08,am,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [19]:
tmp = tmp.reset_index(drop=True)
tmp

,userId,date,amPm,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,am,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
1,user24,2020-08-30,am,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
2,user24,2020-08-31,am,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,coffee,200.0,NaN,NaN
3,user24,2020-09-01,am,2020-09-01 6:20,2020-09-01 6:20,4.0,0.0,4.0,4.0,3.0,5.0,4.0,3.0,coffee,150.0,NaN,NaN
4,user24,2020-09-02,am,2020-09-02 9:02,2020-09-02 9:02,4.0,0.0,4.0,2.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,user06,2020-10-04,am,2020-10-04 12:03,2020-10-04 12:03,4.0,0.0,4.0,4.0,4.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN
611,user06,2020-10-05,am,2020-10-05 12:16,2020-10-05 12:16,4.0,0.0,4.0,4.0,3.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
612,user06,2020-10-06,am,2020-10-06 11:37,2020-10-06 11:37,4.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
613,user06,2020-10-07,am,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
614,user06,2020-10-08,am,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [20]:
tmp = tmp.drop('amPm', axis=1)
tmp

,userId,date,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
1,user24,2020-08-30,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
2,user24,2020-08-31,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,coffee,200.0,NaN,NaN
3,user24,2020-09-01,2020-09-01 6:20,2020-09-01 6:20,4.0,0.0,4.0,4.0,3.0,5.0,4.0,3.0,coffee,150.0,NaN,NaN
4,user24,2020-09-02,2020-09-02 9:02,2020-09-02 9:02,4.0,0.0,4.0,2.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,user06,2020-10-04,2020-10-04 12:03,2020-10-04 12:03,4.0,0.0,4.0,4.0,4.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN
611,user06,2020-10-05,2020-10-05 12:16,2020-10-05 12:16,4.0,0.0,4.0,4.0,3.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
612,user06,2020-10-06,2020-10-06 11:37,2020-10-06 11:37,4.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
613,user06,2020-10-07,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
614,user06,2020-10-08,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [21]:
tmp = tmp.drop(['startInput', 'endInput'], axis=1)
tmp

,userId,date,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,4.0,0.0,3.0,3.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
1,user24,2020-08-30,3.0,2.0,2.0,2.0,3.0,4.0,5.0,2.0,coffee,200.0,NaN,NaN
2,user24,2020-08-31,3.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,coffee,200.0,NaN,NaN
3,user24,2020-09-01,4.0,0.0,4.0,4.0,3.0,5.0,4.0,3.0,coffee,150.0,NaN,NaN
4,user24,2020-09-02,4.0,0.0,4.0,2.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,user06,2020-10-04,4.0,0.0,4.0,4.0,4.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN
611,user06,2020-10-05,4.0,0.0,4.0,4.0,3.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
612,user06,2020-10-06,4.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN
613,user06,2020-10-07,2.0,9.0,4.0,2.0,3.0,5.0,2.0,3.0,coffee,250.0,NaN,NaN
614,user06,2020-10-08,3.0,0.0,4.0,2.0,2.0,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [22]:
tmp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   userId        615 non-null    object
 1   date          615 non-null    object
 2   sleep         615 non-null    float64
 3   sleepProblem  615 non-null    float64
 4   dream         615 non-null    float64
 5   amCondition   615 non-null    float64
 6   amEmotion     615 non-null    float64
 7   pmEmotion     615 non-null    float64
 8   pmStress      615 non-null    float64
 9   pmFatigue     615 non-null    float64
 10  caffeine      282 non-null    object
 11  cAmount(ml)   282 non-null    float64
 12  alcohol       114 non-null    object
 13  aAmount(ml)   113 non-null    float64
dtypes: float64(10), object(4)
memory usage: 67.4+ KB

In [23]:
tmp.value_counts()

userId  date        sleep  sleepProblem  dream  amCondition  amEmotion  pmEmotion  pmStress  pmFatigue  caffeine  cAmount(ml)  alcohol        aAmount(ml)
user01  2020-09-03  3.0    3.0           2.0    2.0          3.0        2.0        2.0       2.0        coffee    1000.0       not specified  1000.0         1
user12  2020-09-04  4.0    0.0           2.0    4.0          3.0        4.0        2.0       4.0        coffee    250.0        soju           350.0          1
user06  2020-09-29  3.0    0.0           4.0    3.0          3.0        2.0        2.0       2.0        coffee    500.0        beer           600.0          1
user10  2020-09-25  2.0    5.0           3.0    1.0          2.0        5.0        4.0       1.0        coffee    680.0        soju           900.0          1
        2020-09-26  5.0    0.0           3.0    1.0          1.0        5.0        4.0       1.0        coffee    400.0        soju           680.0          1
user12  2020-08-30  5.0    7.0           1.0    4.0          5.0        4.0        4.0       4.0        coffee    200.0        soju           200.0          1
        2020-08-31  3.0    2.0           2.0    3.0          3.0        3.0        4.0       3.0        coffee    300.0        soju           200.0          1
        2020-09-01  4.0    5.0           2.0    4.0          3.0        3.0        3.0       3.0        coffee    200.0        beer           1000.0         1
        2020-09-02  2.0    2.0           2.0    2.0          3.0        1.0        1.0       1.0        coffee    150.0        soju           200.0          1
        2020-09-03  3.0    2.0           2.0    2.0          2.0        4.0        3.0       4.0        tea       300.0        beer           500.0          1
        2020-09-14  2.0    7.0           1.0    2.0          2.0        2.0        3.0       3.0        coffee    200.0        beer           700.0          1
user05  2020-09-23  3.0    0.0           4.0    4.0          3.0        4.0        4.0       3.0        coffee    1000.0       not specified  500.0          1
user12  2020-09-16  4.0    2.0           2.0    3.0          3.0        3.0        2.0       1.0        coffee    300.0        soju           200.0          1
user23  2020-09-22  3.0    0.0           2.0    2.0          3.0        5.0        4.0       2.0        coffee    250.0        not specified  300.0          1
user25  2020-09-04  3.0    6.0           2.0    1.0          2.0        3.0        2.0       1.0        coffee    500.0        soju           500.0          1
user26  2020-09-03  3.0    2.0           2.0    2.0          3.0        4.0        4.0       4.0        coffee    400.0        beer           500.0          1
        2020-09-07  4.0    0.0           4.0    4.0          4.0        4.0        3.0       1.0        coffee    200.0        wine           200.0          1
        2020-09-11  4.0    0.0           2.0    2.0          3.0        5.0        4.0       1.0        coffee    300.0        wine&beer      2000.0         1
        2020-09-16  3.0    5.0           2.0    2.0          3.0        4.0        1.0       4.0        coffee    300.0        beer           500.0          1
        2020-09-19  4.0    7.0           1.0    2.0          2.0        4.0        4.0       1.0        coffee    300.0        beer           200.0          1
user06  2020-09-26  4.0    0.0           4.0    4.0          4.0        5.0        5.0       2.0        coffee    300.0        beer           330.0          1
user05  2020-09-21  3.0    0.0           4.0    3.0          3.0        3.0        3.0       3.0        coffee    1000.0       not specified  1000.0         1
user01  2020-09-04  4.0    3.0           2.0    3.0          3.0        4.0        2.0       2.0        coffee    500.0        not specified  500.0          1
        2020-09-20  3.0    3.0           1.0    2.0          2.0        4.0        2.0       2.0        coffee    500.0        not specified  500.0          1
        2020-09-05  3.0    3.0           4.0    2.0          3.0        4.0        4.0       2.0        coffee    1000.0       not specified  1000.0         1
        2020-09-06  3.0    7.0           1.0    3.0          3.0        5.0        2.0       4.0        coffee    1000.0       not specified  1000.0         1
        2020-09-08  4.0    3.0           2.0    3.0          4.0        5.0        4.0       2.0        coffee    1500.0       not specified  1500.0         1
        2020-09-09  2.0    7.0           1.0    3.0          3.0        4.0        4.0       4.0        coffee    500.0        not specified  500.0          1
        2020-09-10  1.0    3.0           2.0    2.0          4.0        5.0        4.0       2.0        coffee    1000.0       not specified  1000.0         1
        2020-09-14  2.0    3.0           2.0    3.0          3.0        5.0        2.0       4.0        coffee    1500.0       not specified  1500.0         1
        2020-09-16  2.0    7.0           1.0    2.0          4.0        4.0        4.0       4.0        coffee    1000.0       not specified  1000.0         1
        2020-09-19  2.0    0.0           4.0    2.0          3.0        4.0        2.0       3.0        coffee    1000.0       not specified  1000.0         1
        2020-09-21  3.0    0.0           1.0    3.0          3.0        3.0        2.0       4.0        coffee    500.0        not specified  500.0          1
user05  2020-09-19  2.0    1.0           4.0    2.0          4.0        3.0        4.0       2.0        coffee    500.0        not specified  300.0          1
user02  2020-08-31  4.0    1.0           2.0    2.0          3.0        3.0        2.0       1.0        coffee    1000.0       soju&beer      500.0          1
        2020-09-18  3.0    7.0           1.0    2.0          2.0        4.0        2.0       2.0        coffee    500.0        soju&beer      1000.0         1
        2020-09-22  4.0    0.0           2.0    3.0          3.0        3.0        2.0       2.0        coffee    500.0        beer           1000.0         1
        2020-09-23  3.0    0.0           2.0    2.0          3.0        4.0        2.0       2.0        coffee    500.0        soju           1500.0         1
user03  2020-09-18  3.0    0.0           2.0    2.0          3.0        3.0        4.0       2.0        coffee    300.0        beer           20000.0        1
        2020-09-19  3.0    0.0           2.0    2.0          3.0        4.0        4.0       2.0        coffee    500.0        beer           800.0          1
user05  2020-09-04  4.0    5.0           4.0    3.0          3.0        4.0        4.0       2.0        coffee    1000.0       not specified  300.0          1
        2020-09-11  2.0    1.0           2.0    2.0          3.0        4.0        4.0       2.0        coffee    1000.0       not specified  500.0          1
user28  2020-09-11  2.0    2.0           4.0    4.0          3.0        5.0        4.0       1.0        coffee    300.0        not specified  300.0          1
Name: count, dtype: int64